spring:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true

  security:
    oauth2:
      client:
        #registration
        registration:
          naver:
            client-name: naver
            client-id: BaRQ5FbWqMb5idafEyls
            client-secret: Pi9dZmanF6
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
          google:
            client-name: google
            client-id: 571093246984-9p5c2smo0m9jm8v5fekh1m8p3ogf5lkj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jwt:
    secret: cxvasdokjqhwoieh9uidshfusdhf9wuefh9we8ry892374ewjkrh23iuh8v9ef3489fn394f9