spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glowrise?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: rhlanf154
  jpa:
    hibernate:
      ddl-auto: update # create, update, none 중 선택
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: BaRQ5FbWqMb5idafEyls
            client-secret: Pi9dZmanF6
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
          google:
            client-name: google
            client-id: 571093246984-9p5c2smo0m9jm8v5fekh1m8p3ogf5lkj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jwt:
    secret: cxvasdokjqhwoieh9uidshfusdhf9wuefh9we8ry892374ewjkrh23iuh8v9ef3489fn394f9